#!/usr/bin/env python3
"""
MedMatch — regenerate embeddings.js (semantic vectors for every job).

Reads DEMO_JOBS out of data.js, embeds each job with the SAME model the
browser uses (all-MiniLM-L6-v2, 384 dims, normalized), quantizes each
vector to int8 + scale in the exact format app.js expects:

    const JOB_EMBEDDINGS = { "job-id": { q: [int8...], s: scale }, ... };

app.js dequantizes with:  x = q * s / 127   (see dequant() in app.js)

Run locally:   pip install sentence-transformers && python make_embeddings.py
Runs weekly in CI via embeddings.yml so new synced jobs always have vectors.
"""
import json
import re

DATA_FILE = "data.js"
OUT_FILE = "embeddings.js"
MODEL = "sentence-transformers/all-MiniLM-L6-v2"  # == Xenova/all-MiniLM-L6-v2 in the browser


def load_jobs(path):
    src = open(path, encoding="utf-8").read()
    m = re.search(r"const DEMO_JOBS\s*=\s*(\[.*?\]);", src, re.S)
    if not m:
        raise SystemExit("ERROR: could not find 'const DEMO_JOBS = [...]' in " + path)
    return json.loads(m.group(1))


def job_text(j):
    """The document we embed for a job — mirrors what a CV would talk about."""
    parts = [
        j.get("title", ""),
        j.get("profession", ""),
        j.get("specialty", ""),
        j.get("city", ""),
        ", ".join(j.get("skills") or []),
        j.get("description", ""),
        ". ".join(j.get("requirements") or []),
    ]
    return ". ".join(p for p in parts if p)


def main():
    from sentence_transformers import SentenceTransformer

    jobs = load_jobs(DATA_FILE)
    print("Embedding %d jobs with %s ..." % (len(jobs), MODEL))
    model = SentenceTransformer(MODEL)
    texts = [job_text(j) for j in jobs]
    vecs = model.encode(texts, normalize_embeddings=True, show_progress_bar=True)

    out = {}
    for j, v in zip(jobs, vecs):
        s = float(max(abs(v))) or 1.0
        q = [int(round(float(x) / s * 127)) for x in v]
        out[j["id"]] = {"q": q, "s": round(s, 6)}

    js = "/* Auto-generated by make_embeddings.py — do not edit by hand. */\n"
    js += "const JOB_EMBEDDINGS = " + json.dumps(out, separators=(",", ":")) + ";\n"
    open(OUT_FILE, "w", encoding="utf-8").write(js)
    print("Wrote %s — %d jobs, %d dims each." % (OUT_FILE, len(out), len(vecs[0])))


if __name__ == "__main__":
    main()
